
_hello:
    path:        /hello/{name}
    defaults:    { _controller: "controllers.hello:doGet"}

_user:
    path:        /user/{id}
    defaults:    { _controller: "controllers.user:getUser"}
    requirements:
        id:  \d+
        
_imdb_search:
    path:        /s/{name}
    defaults:    { _controller: "controllers.imdb:imdbSearch"}
        
        