
_hello:
    path:        /hello/{name}
    defaults:    { _controller: "controllers.hello:doGet"}

_user:
    path:        /user/{id}
    defaults:    { _controller: "controllers.user:getUser"}
    requirements:
        id:  \d+
        
_imdb_api_suggests:
    path:        /s/{name}
    defaults:    { _controller: "controllers.api:imdbSuggests"}
        
_imdb_api_title:
    path:        /t/{title}
    defaults:    { _controller: "controllers.api:imdbTitle"}
        
_home:
    path:       /
    defaults:   {_controller: "controllers.home:index"}